tinyMCE.addI18n('ru.table_dlg', {
    "rules_border": "border",
    "rules_box": "box",
    "rules_vsides": "vsides",
    "rules_rhs": "rhs",
    "rules_lhs": "lhs",
    "rules_hsides": "hsides",
    "rules_below": "below",
    "rules_above": "above",
    "rules_void": "void",
    rules: "Rules",
    "frame_all": "all",
    "frame_cols": "cols",
    "frame_rows": "rows",
    "frame_groups": "groups",
    "frame_none": "none",
    frame: "Frame",
    caption: "Заголовок",
    "missing_scope": "Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.",
    "cell_limit": "Вы превысили максимальное количество ячеек {$cells}.",
    "row_limit": "Вы превысили максимальное количество строк {$rows}.",
    "col_limit": "Вы превысили максимальное количество колонок {$cols}.",
    colgroup: "Col Group",
    rowgroup: "Row Group",
    scope: "Scope",
    tfoot: "Footer",
    tbody: "Тело",
    thead: "Заголовок",
    "row_all": "Обновить все строки в таблице",
    "row_even": "Обновить четные строки в таблице",
    "row_odd": "Обновить нечетные строки в таблице",
    "row_row": "Обновить текущую строку",
    "cell_all": "Обновить все ячейки в таблице",
    "cell_row": "Обновить все ячейки в строке",
    "cell_cell": "Обновить текущую ячейку",
    th: "Заголовок",
    td: "Данные",
    summary: "Summary",
    bgimage: "Фоновое изображение",
    rtl: "Справа налево",
    ltr: "Слева направо",
    mime: "Target MIME Type",
    langcode: "Language Code",
    langdir: "Language Direction",
    style: "Стиль",
    id: "ID",
    "merge_cells_title": "Объединить ячейки таблицы",
    bgcolor: "Фоновый цвет",
    bordercolor: "Border Color",
    "align_bottom": "Снизу",
    "align_top": "Сверху",
    valign: "Вертикальное выравнивание",
    "cell_type": "Тип ячейки",
    "cell_title": "Свойства ячейки таблицы",
    "row_title": "Свойства строки таблицы",
    "align_middle": "По центру",
    "align_right": "Справа",
    "align_left": "Слева",
    "align_default": "По умолчанию",
    align: "Выравнивание",
    border: "Границы",
    cellpadding: "Отступ внутри ячейки",
    cellspacing: "Отступ между ячейками",
    rows: "Строки",
    cols: "Колонки",
    height: "Высота",
    width: "Ширина",
    title: "Вставить/Редактировать таблицу",
    rowtype: "Тип строки",
    "advanced_props": "Дополнительные свойства",
    "general_props": "Основные свойства",
    "advanced_tab": "Дополнительно",
    "general_tab": "Основные",
    "cell_col": "Обновить все ячейки в колонке"
});
