tinyMCE.addI18n('ru.fullpage_dlg', {
    title: "Свойства документа",
    "meta_tab": "Основные",
    "appearance_tab": "Appearance",
    "advanced_tab": "Дополнительные",
    "meta_props": "Meta Information",
    langprops: "Язык и кодировка",
    "meta_title": "Заголовок",
    "meta_keywords": "Ключевые слова",
    "meta_description": "Описание",
    "meta_robots": "Robots",
    doctypes: "Doctype",
    langcode: "Language Code",
    langdir: "Language Direction",
    ltr: "Слева направо",
    rtl: "Справа Налево",
    "xml_pi": "XML Declaration",
    encoding: "Character Encoding",
    "appearance_bgprops": "Background Properties",
    "appearance_marginprops": "Body Margins",
    "appearance_linkprops": "Link Colors",
    "appearance_textprops": "Text Properties",
    bgcolor: "Background Color",
    bgimage: "Background Image",
    "left_margin": "Left Margin",
    "right_margin": "Right Margin",
    "top_margin": "Top Margin",
    "bottom_margin": "Bottom Margin",
    "text_color": "Цвет текста",
    "font_size": "Размер шрифта",
    "font_face": "Font Face",
    "link_color": "Link Color",
    "hover_color": "Hover Color",
    "visited_color": "Visited Color",
    "active_color": "Active Color",
    textcolor: "Цвет",
    fontsize: "Размер шрифта",
    fontface: "Шрифт",
    "meta_index_follow": "Index and Follow the Links",
    "meta_index_nofollow": "Index and Don\'t Follow the Links",
    "meta_noindex_follow": "Do Not Index but Follow the Links",
    "meta_noindex_nofollow": "Do Not Index and Don\'t Follow the Links",
    "appearance_style": "Stylesheet and Style Properties",
    stylesheet: "Stylesheet",
    style: "Style",
    author: "Author",
    copyright: "Copyright",
    add: "Add New Element",
    remove: "Remove Selected Element",
    moveup: "Move Selected Element Up",
    movedown: "Move Selected Element Down",
    "head_elements": "Head Elements",
    info: "Information",
    "add_title": "Title Element",
    "add_meta": "Meta Element",
    "add_script": "Script Element",
    "add_style": "Style Element",
    "add_link": "Link Element",
    "add_base": "Base Element",
    "add_comment": "Comment Node",
    "title_element": "Title Element",
    "script_element": "Script Element",
    "style_element": "Style Element",
    "base_element": "Base Element",
    "link_element": "Link Element",
    "meta_element": "Meta Element",
    "comment_element": "Comment",
    src: "Source",
    language: "Language",
    href: "HREF",
    target: "Target",
    type: "Type",
    charset: "Charset",
    defer: "Defer",
    media: "Media",
    properties: "Properties",
    name: "Name",
    value: "Value",
    content: "Content",
    rel: "Rel",
    rev: "Rev",
    hreflang: "HREF Lang",
    "general_props": "General",
    "advanced_props": "Advanced"
});
