tinyMCE.addI18n('ru.advanced', {
    "underline_desc": "Подчеркнутый (Ctrl+U)",
    "italic_desc": "Курсивный (Ctrl+I)",
    "bold_desc": "Жирный (Ctrl+B)",
    dd: "Definition Description",
    dt: "Definition Term ",
    samp: "Пример кода",
    code: "Код",
    blockquote: "Цитата",
    h6: "Заголовок 6",
    h5: "Заголовок 5",
    h4: "Заголовок 4",
    h3: "Заголовок 3",
    h2: "Заголовок 2",
    h1: "Заголовок 1",
    pre: "Предформатированный",
    address: "Адрес",
    div: "DIV",
    paragraph: "Paragraph",
    block: "Форматирование",
    fontdefault: "Шрифт",
    "font_size": "Размер шрифта",
    "style_select": "Стили",
    "anchor_delta_height": "",
    "anchor_delta_width": "",
    "charmap_delta_height": "",
    "charmap_delta_width": "",
    "colorpicker_delta_height": "",
    "colorpicker_delta_width": "",
    "link_delta_height": "",
    "link_delta_width": "",
    "image_delta_height": "",
    "image_delta_width": "",
    "more_colors": "Другие цвета...",
    "toolbar_focus": "Перейти на панель инструментов - Alt+Q, Перейти в редактор - Alt-Z, Перейти в строку состояния - Alt-X",
    newdocument: "Вы действительно желаете удалить текущее содержимое?",
    path: "Путь",
    "clipboard_msg": "Копировать/Вырезать/Вставить недоступно в Mozilla и Firefox.\nВы хотите получить больше информации по этому вопросу?",
    "blockquote_desc": "Цитата",
    "help_desc": "Помощь",
    "newdocument_desc": "Новый документ",
    "image_props_desc": "Свойства изображения",
    "paste_desc": "Вставить (Ctrl+V)",
    "copy_desc": "Копировать (Ctrl+C)",
    "cut_desc": "Вырезать (Ctrl+X)",
    "anchor_desc": "Вставить/Редактировать якорь",
    "visualaid_desc": "Показать/Скрыть контуры невидимых элементов",
    "charmap_desc": "Вставка специальных символов",
    "backcolor_desc": "Выбрать цвет фона",
    "forecolor_desc": "Выбрать цвет текста",
    "custom1_desc": "Введите произвольное описание",
    "removeformat_desc": "Очистить форматированние",
    "hr_desc": "Вставить горизонтальную линию",
    "sup_desc": "Верхний индекс",
    "sub_desc": "Нижний индекс",
    "code_desc": "Редактировать код HTML",
    "cleanup_desc": "Cleanup Messy Code",
    "image_desc": "Вставить/Редактировать изображение",
    "unlink_desc": "Удалить гиперссылку",
    "link_desc": "Вставить/Редактировать гиперссылку",
    "redo_desc": "Повторить (Ctrl+Y)",
    "undo_desc": "Отменить (Ctrl+Z)",
    "indent_desc": "Увеличить отступ",
    "outdent_desc": "Уменьшить отступ",
    "numlist_desc": "Вставить/Удалить нумерованный список",
    "bullist_desc": "Вставить/Удалить маркированный список",
    "justifyfull_desc": "По ширине",
    "justifyright_desc": "По правому краю",
    "justifycenter_desc": "По центру",
    "justifyleft_desc": "По левому краю",
    "striketrough_desc": "Зачеркнутый",
    "help_shortcut": "Press ALT-F10 for toolbar. Press ALT-0 for help",
    "rich_text_area": "Поле форматированного текста",
    "shortcuts_desc": "Accessability Help",
    toolbar: "Панель инструментов"
});
