tinyMCE.addI18n('ru.advanced_dlg', {
    "link_list": "Список гиперссылок",
    "link_is_external": "Введенный URL ссылается на внешний ресурс. Вы хотите добавить необходимый префикс http:// ?",
    "link_is_email": "Введенный URL является email адресом. Вы хотите добавить необходимый префикс mailto: ?",
    "link_titlefield": "Заголовок",
    "link_target_blank": "Открыть гиперссылку в новом окне",
    "link_target_same": "Открыть гиперссылку в текущем окне",
    "link_target": "Target",
    "link_url": "URL гиперссылки",
    "link_title": "Вставить/Редактировать гиперссылку",
    "image_align_right": "Справа",
    "image_align_left": "Слева",
    "image_align_textbottom": "Текст снизу",
    "image_align_texttop": "Текст сверху",
    "image_align_bottom": "Снизу",
    "image_align_middle": "По середине",
    "image_align_top": "Сверху",
    "image_align_baseline": "По базовой линии",
    "image_align": "Выравнивание",
    "image_hspace": "Горизонтальный промежуток",
    "image_vspace": "Вертикальный промежуток",
    "image_dimensions": "Размеры",
    "image_alt": "Описание изображения",
    "image_list": "Список изображений",
    "image_border": "Граница",
    "image_src": "URL изображения",
    "image_title": "Вставить/Редактировать изображение",
    "charmap_title": "Выбрать специальный символ",
    "charmap_usage": "Дла навигации используйте стрелки влево/вправо.",
    "colorpicker_name": "Название:",
    "colorpicker_color": "Цвет:",
    "colorpicker_named_title": "Именованные цвета",
    "colorpicker_named_tab": "Named",
    "colorpicker_palette_title": "Palette Colors",
    "colorpicker_palette_tab": "Palette",
    "colorpicker_picker_title": "Color Picker",
    "colorpicker_picker_tab": "Picker",
    "colorpicker_title": "Выберите цвет",
    "code_wordwrap": "Переносить строки",
    "code_title": "Редактор HTML кода",
    "anchor_name": "Имя якоря",
    "anchor_title": "Вставить/Редактировать якорь",
    "about_loaded": "Подключенные плагины",
    "about_version": "Версия",
    "about_author": "Автор",
    "about_plugin": "Плагин",
    "about_plugins": "Плагины",
    "about_license": "Лицензия",
    "about_help": "Помощь",
    "about_general": "About",
    "about_title": "О программе TinyMCE",
    "anchor_invalid": "Пожалуйста, укажите корректное имя якоря.",
    "accessibility_help": "Accessibility Help",
    "accessibility_usage_title": "General Usage",
    "invalid_color_value": "Некорректное значение цвета",
    "": ""
});
