tinyMCE.addI18n('ru.xhtmlxtras_dlg', {
    "attribs_title": "Вставить/Редактировать атрибуты",
    "option_rtl": "Справа налево",
    "option_ltr": "Слева направо",
    "insert_date": "Вставить текущие дату/время",
    remove: "Удалить",
    "title_cite_element": "Элемент цитата",
    "title_abbr_element": "Элемент аббревиатура",
    "title_acronym_element": "Элемент сокращения",
    "title_del_element": "Элемент удаления",
    "title_ins_element": "Элемент ввода",
    "fieldset_events_tab": "Element Events",
    "fieldset_attrib_tab": "Element Attributes",
    "fieldset_general_tab": "Основные настройки",
    "events_tab": "События",
    "attrib_tab": "Атрибуты",
    "general_tab": "Основные",
    "attribute_attrib_tab": "Атрибуты",
    "attribute_events_tab": "События",
    "attribute_label_accesskey": "AccessKey",
    "attribute_label_tabindex": "TabIndex",
    "attribute_label_langcode": "Language",
    "attribute_option_rtl": "Справа налево",
    "attribute_option_ltr": "Слева направо",
    "attribute_label_langdir": "Направление текста",
    "attribute_label_datetime": "Дата/Время",
    "attribute_label_cite": "Цитировать",
    "attribute_label_style": "Стиль",
    "attribute_label_class": "Class",
    "attribute_label_id": "ID",
    "attribute_label_title": "Заголовок"
});
