tinyMCE.addI18n('ru.advanced_dlg', {
    "link_list": "������ �����������",
    "link_is_external": "��������� URL ��������� �� ������� ������. �� ������ �������� ����������� ������� http:// ?",
    "link_is_email": "��������� URL �������� email �������. �� ������ �������� ����������� ������� mailto: ?",
    "link_titlefield": "���������",
    "link_target_blank": "������� ����������� � ����� ����",
    "link_target_same": "������� ����������� � ������� ����",
    "link_target": "Target",
    "link_url": "URL �����������",
    "link_title": "��������/������������� �����������",
    "image_align_right": "������",
    "image_align_left": "�����",
    "image_align_textbottom": "����� �����",
    "image_align_texttop": "����� ������",
    "image_align_bottom": "�����",
    "image_align_middle": "�� ��������",
    "image_align_top": "������",
    "image_align_baseline": "�� ������� �����",
    "image_align": "������������",
    "image_hspace": "�������������� ����������",
    "image_vspace": "������������ ����������",
    "image_dimensions": "�������",
    "image_alt": "�������� �����������",
    "image_list": "������ �����������",
    "image_border": "�������",
    "image_src": "URL �����������",
    "image_title": "��������/������������� �����������",
    "charmap_title": "������� ����������� ������",
    "charmap_usage": "��� ��������� ����������� ������� �����/������.",
    "colorpicker_name": "��������:",
    "colorpicker_color": "����:",
    "colorpicker_named_title": "����������� �����",
    "colorpicker_named_tab": "�����������",
    "colorpicker_palette_title": "������� ������",
    "colorpicker_palette_tab": "�������",
    "colorpicker_picker_title": "����� �����",
    "colorpicker_picker_tab": "�����",
    "colorpicker_title": "�������� ����",
    "code_wordwrap": "���������� ������",
    "code_title": "�������� HTML ����",
    "anchor_name": "��� �����",
    "anchor_title": "��������/������������� �����",
    "about_loaded": "������������ �������",
    "about_version": "������",
    "about_author": "�����",
    "about_plugin": "������",
    "about_plugins": "�������",
    "about_license": "��������",
    "about_help": "������",
    "about_general": "About",
    "about_title": "� ��������� TinyMCE",
    "anchor_invalid": "����������, ������� ���������� ��� �����.",
    "accessibility_help": "Accessibility Help",
    "accessibility_usage_title": "General Usage",
    "invalid_color_value": "������������ �������� �����",
    "": ""
});
