tinyMCE.addI18n('ru.style_dlg', {
    "text_lineheight": "Высота строки",
    "text_variant": "Variant",
    "text_style": "Стиль",
    "text_weight": "Вес",
    "text_size": "Размер",
    "text_font": "Шрифт",
    "text_props": "Текст",
    "positioning_tab": "Позиционирование",
    "list_tab": "Список",
    "border_tab": "Граница",
    "box_tab": "Box",
    "block_tab": "Block",
    "background_tab": "Фон",
    "text_tab": "Текст",
    apply: "Применить",
    toggle_insert_span: "Insert span at selection",
    title: "Редактировать стиль CSS",
    clip: "Clip",
    placement: "Placement",
    overflow: "Overflow",
    zindex: "Z-index",
    visibility: "Visibility",
    "positioning_type": "Type",
    position: "Position",
    "bullet_image": "Bullet Image",
    "list_type": "Type",
    color: "Цвет",
    height: "Высота",
    width: "Ширина",
    style: "Стиль",
    margin: "Margin",
    left: "Left",
    bottom: "Bottom",
    right: "Right",
    top: "Top",
    same: "Same for All",
    padding: "Padding",
    "box_clear": "Clear",
    "box_float": "Float",
    "box_height": "Height",
    "box_width": "Width",
    "block_display": "Display",
    "block_whitespace": "Whitespace",
    "block_text_indent": "Text Indent",
    "block_text_align": "Text Align",
    "block_vertical_alignment": "Vertical Alignment",
    "block_letterspacing": "Letter Spacing",
    "block_wordspacing": "Word Spacing",
    "background_vpos": "Vertical Position",
    "background_hpos": "Horizontal Position",
    "background_attachment": "Attachment",
    "background_repeat": "Repeat",
    "background_image": "Background Image",
    "background_color": "Background Color",
    "text_none": "None",
    "text_blink": "Blink",
    "text_case": "Case",
    "text_striketrough": "Strikethrough",
    "text_underline": "Underline",
    "text_overline": "Overline",
    "text_decoration": "Decoration",
    "text_color": "Color",
    text: "Text",
    background: "Background",
    block: "Block",
    box: "Box",
    border: "Border",
    list: "List"
});
